### PR TITLE
fix(gta-core-five): invalid bounding volume hierarchy

### LINKED ISSUE #3155: table-ohio-emma crash
### What happened?

Is happening to some people (not all the people) when u go to a certain zone, but not always in the same zone but surrounding zone.

Crash with a table-ohio-emma code.

### Expected result

No crashing?

### Reproduction steps

The only way to reproduce this is with my server or in my server driving in a road close to bank pacific, autoexotics, cityhall in circles.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM 12767 b3258

### Additional information

Here the crash dump.
[CfxCrashDump_2025_02_14_18_12_55.zip](https://github.com/user-attachments/files/18803260/CfxCrashDump_2025_02_14_18_12_55.zip)

And i let u the image of the crash.
Image

### PR DESCRIPTION
**Pull request by DaniGP17**
### Goal of this PR
Fix a crash that occurred in the call to the `CalcClosestLeafDistance` function that is responsible for traversing the bvh to find the squared distance to the closest leaf node from the given position.
The function could crash if the bvh or bvhNode pointer was null.

### How is this PR achieving the goal
Adding a check before the original call of the function.

### This PR applies to the following area(s)
FiveM

### Successfully tested on
**Game builds:** 1604, 3095, 3407

**Platforms:** Windows, Linux

### Checklist
- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues
fixes #3155

### CODE REVIEW

File: code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp [hunk 1]
```diff
@@ -41,6 +41,24 @@ namespace rage {
...
+		__int16 m_AABBMin[3];
+		__int16 m_AABBMax[3];
+		unsigned __int16 m_NodeData;
+		unsigned __int8 m_PolygonCount;
+	};
+
+	struct phOptimizedBvh
+	{
+		phOptimizedBvhNode* bvhNode;
+	};
```
Comment (Nobelium-cfx) [inline code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp:56]: Nit: this structure is incomplete. No need to fill it all, but lets add a padding for the remaining fields size (i.e. `char pad[120]`);

Comment (DaniGP17) [reply code/components/gta-core-five/src/CrashFixes.SelfCollision.cpp:57]: Added the padding as suggested, thanks!
