### PR TITLE
tweak(natives/rpc): Use client-native names and apply aliases

### LINKED ISSUE #2447: Error on SetPedHairColor - 0xBB43F090
### What happened?

When trying to set the ped hair colour via the server side I get (global SetPedHairColor) doesn't exist
image

### Expected result

execute the native SetPedHairColor

### Reproduction steps

When trying to apply SetPedHairColor on character load it crashes.

### Importancy

Crash

### Area(s)

FiveM

### Specific version(s)

FiveM/7827

### Additional information

_No response_

### LINKED ISSUE #2549: Server side RPC native `SetPedHairColor` doesn't exist
### What happened?

Updated to the latest version of the server 8187 and the native no longer exists.

When looking at the documention for the client sided which still has SetPedHairColor (Ref: 0xBB43F090) and clicking the link to the server side version it takes me to SetPedHairTint (Ref: 0x4CFFC65454C93A49) however when using this too, it gives the same error about not existing.

image

image

### Expected result

To be able to set the player hair colour from the server side without crashing.

### Reproduction steps

1. Download the latest version of the server or version 8187
2. Try setting the ped hair colour server side using `SetPedHairColor(index, colour, highlight)` or `SetPedHairTint(index, color, highlight)`

### Importancy

Crash

### Area(s)

FXServer, OneSync

### Specific version(s)

Server 8187 on both linux and windows

### Additional information

 Seems to be an issue with all artifacts from the last two or three months.

### PR DESCRIPTION
**Pull request by tens0rfl0w**
### Goal of this PR

Commit https://github.com/citizenfx/natives/commit/e6f473573f6eb7e2921b2ef48668117cbbe84bbb changed the native name from '_SET_PED_HAIR_COLOR' to 'SET_PED_HAIR_TINT' which makes the RPC native definition invalid.

### How is this PR achieving the goal

We now also check for alias matches when generating RPC decl. in codegen and apply client-native aliases to RPC natives. This allows us to keep RPC native naming in sync with client-native changes while maintaining backward compatibility with old native naming (like on the client side).

### This PR applies to the following area(s)

FiveM, Natives (RPC)

### Successfully tested on

**Game builds:** 2699 

**Platforms:** Windows

### Checklist

- [x] Code compiles and has been tested successfully.
- [x] Code explains itself well and/or is documented.
- [x] My commit message explains what the changes do and what they are for.
- [x] No extra compilation warnings are added by these changes.

### Fixes issues
fixes #2549
fixes #2447
fixes https://forum.cfx.re/t/5226975

### CODE REVIEW

**Comment by DaniGP17** [comment]
Why some functions names start with `_`?

**Comment by AvarianKnight** [comment]
Names that start with underscore mean that the name isn't known.

**Comment by freedy69** [comment]
maybe `CALL_MINIMAP_SCALEFORM_FUNCTION` can also be renamed to `BEGIN_SCALEFORM_MOVIE_METHOD_ON_MINIMAP`?

**Comment by freedy69** [comment]
> > maybe `CALL_MINIMAP_SCALEFORM_FUNCTION` can also be renamed to `BEGIN_SCALEFORM_MOVIE_METHOD_ON_MINIMAP`?
> 
> 
> 
> Why should this native be renamed? This is a custom native, not a base-game native.
> 
> 
> 
> Also, PRs are *generally* not the best place to suggest other stuff as this PR is about RPC natives.

Im just saying because it would fit naming formatting of other scaleform natives. Would make it easier to read, im not really suggesting, more so pointing out

**Comment by gottfriedleibniz** [comment]
To avoid breaking compatibility here, it *should* be safe (i.e., requires testing) to update [getNative](https://github.com/citizenfx/fivem/blob/ddd4810161d4285918d52772b6d2cfce12816282/ext/natives/codegen.lua#L177) to also search through aliases, e.g.,

```lua
local function getNative(nativeName)
	-- get the native
	for k, v in ipairs(natives) do
		if #v.apiset == 0 or v.apiset[1] == 'client' then
			if v.name == nativeName then
				return v
			end

			for _,aliasName in ipairs(v.aliases) do
				if nativeName == aliasName then
					return v
				end
			end
		end
	end
	return nil
end
```

Updating this script to use a reverse name lookup would probably be better. That can be done later though.

File: ext/natives/codegen.lua [hunk 1]
```diff
@@ -281,67 +285,70 @@ function rpcEnvironment.context_rpc(nativeName)
...
-		codeEnvironment.returns('void')
-		curNative.rpc = true
-		curNative.ogHash = n.hash
+	removeServerNative(n.name)
+	codeEnvironment.native(n.name)
+	codeEnvironment.arguments(n.arguments)
+	codeEnvironment.apiset('server')
+	codeEnvironment.returns('void')
+	for _, aliasName in ipairs(n.aliases) do
+		codeEnvironment.alias(aliasName)
```
Comment (gottfriedleibniz) [inline ext/natives/codegen.lua:294]: Including aliases will also require `removeServerNative(aliasName)`, same applies to the other cases `codeEnvironment` below. Otherwise the server files will contain duplicate definitions and MonoV2 won't compile.

Comment (gottfriedleibniz) [reply ext/natives/codegen.lua:294]: Can you double check after clearing all intermediate files, e.g., `rm -rf ext/natives/inp ext/natives/out`? MonoV2's compilation will give me, for example,

```cs
public static void SetPedHairColor(int ped, int colorID, int highlightColorID)
{
    NativesImpl.void_0xbb43f090(N64.Val(ped), N64.Val(colorID), N64.Val(highlightColorID));
}

// ...

public static void SetPedHairColor(int ped, int colorID, int highlightColorID) => SetPedHairTint(ped, colorID, highlightColorID);
```

Comment (gottfriedleibniz) [reply ext/natives/codegen.lua:294]: Ah. Apparently `native-decls/native_md` not being cleaned properly - leaving old definitions around (on both computers I tested).
